# dataset/
# ├── images/
# │   ├── visible/    # Store  visible light images
# │   │   ├── image1.jpg  
# │   │   └── image2.jpg
# │   │   └── ...      
# │   └── infrared/  #  Store  visible light images
# │       ├── image1.jpg   
# │       └── image2.jpg  
# │       └── ...         
# └── labels/
#     ├── visible/  # Store  visible light labels
#     │   ├── image1.txt   
#     │   └── image2.txt 
#     └── infrared/  # Store  infrared light labels
#         ├── image1.txt
#         └── image2.txt    
        

# VEDAI.yaml

# train:  
# val:  
train:  D:\robotmaster\2026\RGBD\yolov11_RGBT\dataset\train.txt  
val:  D:\robotmaster\2026\RGBD\yolov11_RGBT\dataset\val.txt 

# number of classes
nc: 1

# class names
names: ['volleyball']

